helidocs/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover() 

urlpatterns = patterns('',
    # Example:

    (r'^findfreeseats/$','helidocs.diary.views.findfreeseats'),
    (r'^findfreeseats/(.*)','helidocs.diary.views.findfreeseats'),

    (r'^get_voucher/','helidocs.diary.views.get_voucher'),
    (r'^get_student/','helidocs.diary.views.get_student'),
    (r'^get_voucher_contacts/(.*)','helidocs.diary.views.get_voucher_contacts'),
    (r'^get_student_contacts/(.*)','helidocs.diary.views.get_student_contacts'),
    (r'^calendar/$','helidocs.diary.views.calendar'),
    (r'^calendar/(.*)','helidocs.diary.views.calendar'),
    (r'^calendaradd/(.*)','helidocs.diary.views.calendaradd'),
    (r'^grouponadd/(.*)','helidocs.diary.views.grouponadd'),
    (r'^calendaredit/(?P<pID>\d+)/$','helidocs.diary.views.calendaredit'),
    (r'^daytoview/$','helidocs.diary.views.daytoview'),
    (r'^daytoview/(.*)','helidocs.diary.views.daytoview'),
    (r'^setcomplete/(.*)','helidocs.diary.views.SetComplete'),

    (r'^grouponbookin/$','helidocs.diary.views.grouponbookin'),
    (r'^grouponbookin/(.*)','helidocs.diary.views.grouponbookin'),
    (r'^home/','helidocs.diary.views.homepage'),
    (r'^$','helidocs.diary.views.homepage'),


    (r'^static/admin/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '/home/technomics/venvs/helidocs/lib/python2.7/site-packages/django/contrib/admin/static/admin'}),
    (r'^admin/jsi18n/', 'django.views.i18n.javascript_catalog'),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '/home/technomics/venvs/helidocs/helidocs/static'}),
    # (r'^helidocs/', include('helidocs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
#    (r'^accounts/', include('registration.urls')),
)

helidocs/diary/models.py
from django.db import models

class ship(models.Model):
    owner=models.CharField('owner',max_length=200)
    type=models.CharField('type',max_length=200)
    model=models.CharField('model',max_length=200)
    callsign=models.CharField('callsign',max_length=60)
    serialno=models.CharField('serialno',max_length=200)
    registration=models.CharField('registration',max_length=200)
    engine_id=models.BigIntegerField('engine_id')
    hours=models.DecimalField('hours',max_digits=10,decimal_places=1)
    airframehoursoffset=models.DecimalField('airframehoursoffset',max_digits=10,decimal_places=1)
    cycles=models.SmallIntegerField('cycles')
    lastflight=models.DateField('lastflight')
    lastoverhaul=models.DateField('lastoverhaul',null=True)
    manufactured=models.DateField('manufactured',null=True)
    lastdatcon=models.DecimalField('lastdatcon',max_digits=6,decimal_places=1)
    nextmaintdatcon=models.DecimalField('nextmaindatcon',max_digits=6,decimal_places=1)
    nextmaintdate=models.DateField('nextmaindate',null=False)
    nextmaintreason=models.CharField('Next Maintenance Reason',max_length=200)
    arcdate=models.DateField('ARC Date',null=False)
    owned=models.BooleanField('Ship still owned')
    crs=models.CharField('CRS',max_length=255)
    def __str__(self):
        return '%s %s: %s'%(self.type,self.model,self.registration)



class event(models.Model):
    starttime=models.DateTimeField('Start Time')
    duration=models.IntegerField('Duration',blank=True,null=True)
    ship=models.ForeignKey(ship,verbose_name="Helicopter",blank=True,null=True)
    voucher=models.CharField('Voucher',max_length=200,blank=True,null=True)
    security=models.CharField('Security',max_length=200,blank=True,null=True)
    name=models.CharField('Name',max_length=200)
    seats=models.IntegerField('Seats',default=1,null=False)
    mobile=models.CharField('mobile',max_length=200)
    email=models.CharField('email',max_length=200,blank=True,null=True)
    details=models.CharField('Details',max_length=200,blank=True,null=True)
    captain=models.CharField('Captain',max_length=200,blank=True,null=True)
    notes=models.TextField('Notes',blank=True,null=True)
    cancelled=models.BooleanField('Cancelled')
    completed=models.BooleanField('Completed')
    source=models.CharField('Source',max_length=200,blank=True,null=True)
    def __str__(self):
        return '%s: %s %s %s'%(self.starttime,self.duration,self.name,self.details)


# Create your models here.

helidocs/diary/views.py
# Create your views here.
import datetime
from django.shortcuts import HttpResponse,redirect
from django.shortcuts import render_to_response,get_object_or_404
from helidocs.diary.models import event
from helidocs.diary.models import ship
from helidocs.widgets.ukdate import ukdatetime,ukdate
from calendar import monthrange
from django.views.decorators.csrf import csrf_exempt
from django.core.context_processors import csrf
from django.forms import ModelForm,Textarea,TextInput
from django import forms
from helidocs.widgets.widgets import MyDateWidget,MyDateTimeWidget

class NewGroupOnEventForm(ModelForm):
    starttime=forms.DateTimeField(label="Start Time",input_formats=['%H:%M %d/%m/%Y','%H:%M %d/%m/%y','%H:%M:%S %d/%m/%Y'],widget=MyDateTimeWidget())
    voucher=forms.CharField(label='GroupOn Voucher Number',required=True) #,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    security=forms.CharField(label='GroupOn Security Number',required=True) #,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    voucher2=forms.CharField(label='GroupOn2 Voucher Number',required=False) #,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    security2=forms.CharField(label='GroupOn2 Security Number',required=False) #,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    voucher3=forms.CharField(label='GroupOn3 Voucher Number',required=False) #,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    security3=forms.CharField(label='GroupOn3 Security Number',required=False) #,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    create=forms.BooleanField(label="Create Seat Duplicates",required=False,initial=True)

    class Meta:
        model=event
        widgets = {
            'voucher': TextInput(attrs={'size': 40}),
            'details': TextInput(attrs={'size': 40}),
            'email': TextInput(attrs={'size': 40}),
            'notes': Textarea(attrs={'cols': 40, 'rows': 2}),
            'source': forms.widgets.HiddenInput(),
            }


class NewEventForm(ModelForm):
    starttime=forms.DateTimeField(label="Start Time",input_formats=['%H:%M %d/%m/%Y','%H:%M %d/%m/%y','%H:%M:%S %d/%m/%Y'],widget=MyDateTimeWidget())
    #    exercises=forms.CharField(required=False,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    #    comments = forms.CharField(required=False,widget=forms.Textarea(attrs={'rows':6, 'cols':60}))
    create=forms.BooleanField(label="Create Seat Duplicates",required=False,initial=True)
    class Meta:
        model=event
        exclude = ('security',)
        widgets = {
            'voucher': TextInput(attrs={'size': 40}),
            'email': TextInput(attrs={'size': 40}),
            'mobile': TextInput(attrs={'size': 40}),
            'details': TextInput(attrs={'size': 40}),
            'notes': Textarea(attrs={'cols': 40, 'rows': 2}),
            'source': forms.widgets.HiddenInput(),

            }

class NewEventEditForm(ModelForm):
    starttime=forms.DateTimeField(label="Start Time",input_formats=['%H:%M %d/%m/%Y','%H:%M %d/%m/%y','%H:%M:%S %d/%m/%Y'],widget=MyDateTimeWidget())
    #    exercises=forms.CharField(required=False,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    #    comments = forms.CharField(required=False,widget=forms.Textarea(attrs={'rows':6, 'cols':60}))
    security=forms.CharField(label='Groupon Security No.',required=False) #,widget=forms.Textarea(attrs={'rows':3, 'cols':60}))
    duplicate=forms.BooleanField(label="Duplicate (Don't Edit)",required=False)
    class Meta:
        model=event
        exclude = ('seats',)
        widgets = {
            'email': TextInput(attrs={'size': 40}),
            'voucher': TextInput(attrs={'size': 40}),
            'details': TextInput(attrs={'size': 40}),
            'mobile': TextInput(attrs={'size': 40}),
            'notes': Textarea(attrs={'cols': 40, 'rows': 2}),
            'source': forms.widgets.HiddenInput(),
            }



def subtract_date(date, year=0, month=0):
    year, month = divmod(year*12 + month, 12)
    if date.month <= month:
        year = date.year - year - 1
        month = date.month - month + 12
    else:
        year = date.year - year
        month = date.month - month
    return date.replace(year = year, month = month,day=1)

def add_date(date, month=0):
    if date.month+month>12:
        year = date.year+1
        month = date.month + month -12
    else:
        year = date.year
        month = date.month + month
    return date.replace(year = year, month = month)

def homepage(request):
    c={'user':request.user}
    return render_to_response('diary/homepage.html',c)

def calendar(request,pID='0'):
    c={'user':request.user}
    try:
        y,m=pID.split('-')
        r=datetime.datetime(int(y),int(m),1,0,0,0)
    except:
        r=ukdatetime()

    s=r.replace(day=1,hour=0,minute=0,second=0)
    back=s+datetime.timedelta(days=-2)
    last=monthrange(s.year,s.month)[1]

    c.update({'date':s.strftime('%B %Y')})
    days=[]
    skip=s.weekday()
    count=0
    day=1
    y=r.year
    m=r.month+1
    if m==13:
        y=r.year+1
        m=1

    stx=datetime.datetime(r.year,r.month,1,0,0,0).strftime('%Y-%m-%d')
    etx=datetime.datetime(y,m,1,0,0,0).strftime('%Y-%m-%d')
    c['back']=back.strftime('%Y-%m')
    c['forwards']=etx[:7]
    startfuel=0
    dial=34634
    ev=event.objects.filter(starttime__gte=stx,starttime__lt=etx).order_by("starttime")
    stx=datetime.datetime(r.year,r.month,1,0,0,0)

    for q in range(1,7):
        ee=[]
        for x in range(1,8):
            dday=""
            events=""
            link=""
            etx=stx+datetime.timedelta(days=1)
            if count>=skip and day<=last:
                dday=day
                day+=1
                link=stx.strftime('%Y-%m-%d')
                for r in ev:
                    if r.starttime>=stx and r.starttime<etx:
                        if events:
                            events+='<br>'
                        heli=""
                        if r.ship:
                            heli=" [%s]"%(r.ship.model[:3])
                        else:
                            events+='<font color="red">'
                        if r.cancelled:
                            events+='<strike>'
                        captain=''
                        if r.captain:
                            captain="(%s)"%(r.captain)
                        name='<font color="purple"><b>'+r.voucher+"</b> "+r.name+'</font>'
                        if r.voucher and r.voucher.find('(voucher)')!=-1:
                            name='<font color="purple">'+r.voucher.replace('(voucher)','')+'</font>'
                        if r.security:
                            name='<font color="#CC0066"><b>[GO] '+r.voucher+"</b> "+r.name+'</font>'
                        ttdelta=r.duration
                        if not ttdelta:
                            ttdelta=0
                        if r.completed:
                            events+='<font color="#009933"><b>'
                        events+='''<strong><a href="javascript:void(0)" onClick="OpenNewEvent('/calendaredit/'''+str(r.id)+'''');return false;">'''+'%s-%s:</a></strong> %s[%d] %s %s%s'%(r.starttime.strftime('%H:%M'),(r.starttime+datetime.timedelta(minutes=ttdelta)).strftime('%H:%M'),heli,ttdelta,name,r.details,captain)
                        if not r.ship:
                            events+='</font>'
                        if r.cancelled:
                            events+='</strike>'
                        if r.completed:
                            events+='</b></font>'

                stx=stx+datetime.timedelta(days=1)
            count+=1
            ee.append({'day':dday,'link':link,'event':events})
        days.append(ee)
    c['days']=days
    return render_to_response('diary/calendar.html',c)

def calendaradd(request,pID=''):
    c={'user':request.user}
    c.update(csrf(request))
    starttime=ukdatetime()
    heli='0'
    if pID:
        if pID.find('*')!=-1:
            pXX,heli=pID.split('*')
        else:
            pXX=pID
        try:
            starttime=datetime.datetime.strptime(pXX,'%Y-%m-%d:%H:%M')

        except:
            try:
                starttime=datetime.datetime.strptime(pXX,'%Y-%m-%d: 12:00:00')
            except:
                y,m,d=pXX.split('-')
                starttime=datetime.datetime(int(y),int(m),int(d),12,00,00)

    message="Please Correct Error and Resubmit"
    if request.method=="GET":
        newevent=NewEventForm(initial={'starttime': starttime,'ship': str(heli)})#initial={'ship': pID,'datcon':s.lastdatcon,'date':lastflown}
        #maint.fields['ship']=pID
        message='Enter the New Event'
        c.update({'newevent':newevent})
    elif request.method=="POST":
        if request.POST["submit"] == "Submit Event":
            newevent=NewEventForm(request.POST)
            if newevent.is_valid():
                original_event=newevent.save()

                #create entries if there is more than one seat on voucher
                obj=event.objects.get(pk=original_event.id)
                for x in range(1,original_event.seats):
                    obj.id=None
                    obj.save(force_insert=True)

                #now check to see if a voucher was involved
                v=request.POST["voucher"]
                if v and v.find('(voucher)')!=-1:
                    vno=v[:v.find(' ')]
                    #print vno
                    entry = voucher.objects.get(number=vno)
                    #print entry
                    if entry:
                        if request.POST.has_key("cancelled"):
                            entry.bookeddate=None
                        else:
                            dt=datetime.datetime.strptime(request.POST["starttime"],"%H:%M %d/%m/%Y")
                            entry.bookeddate=dt
                        if request.POST.has_key("completed"):
                            dt=datetime.datetime.strptime(request.POST["starttime"],"%H:%M %d/%m/%Y")

helidocs/templates/diary/calendar.html
{%extends "diary/calendar_base.html" %}
{% load custom_templates %}

{%block title%}Calendar{%endblock%}

{%block css%}
<link href="/static/css/screen.css" rel="stylesheet" type="text/css" media="screen, projection" />
<link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print" />

    <style type="text/css">
     .helidocs table {border-left: 0px;font-family:Verdana;font-size: 11px;text-align: right;}

    /* HEADER */
      #header {background: #800080;color: #ffc;overflow: hidden;}
      #header a:link, #header a:visited {color: white;}
      #header a:hover {text-decoration: underline;}
      #branding h1 {font-family:Verdana;font-size: 14px;padding: 0 10px;margin: 8px 0;font-weight: normal;color: #ffffff;}
      #branding h2 {padding: 0 10px;font-size: 14px;margin: -8px 0 8px 0;font-weight: normal; color: #ffc;}
      #user-tools {font-family:Verdana;position: absolute;top: 0;right: 0;padding: 1.2em 10px;font-size: 11px;text-align: right;}
    </style>


{%endblock%}

{%block headerscripts%}
<script type="text/javascript">
function OpenNewEvent(sURL)
     {
       var newwindow;
       newwindow = window.open(sURL,"Enter New Event","height=550,width=540,toolbar=no,location=no,scrollbars=yes,statusbar=no,resizable=no");
       if (window.focus) {
        newwindow.focus()
       }
     }
</script>
{%endblock%}


{%block content%}
    <!-- Header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name"> <a href="{% url "helidocs.diary.views.calendar" %}">Helicopter Docs</a></h1>
        </div>
        <div id="user-tools">
            Welcome,
            <strong>{{  user.username }}</strong>.
           <!-- <a href="/admin/password_change/">
                Change password</a> / -->
            <a href="/logoutuser/">
                Log out</a>
        </div>
    </div>
    <hr>
    {% for breadcrumb in request.breadcrumbs %}
        <a href="{{ breadcrumb.url }}">{{ breadcrumb.name }}</a>{% if not forloop.last %} >> {% endif %}
        {% endfor %}
    <!-- END Header -->


<table cellspacing="0">
	<caption><a href="{% url "helidocs.diary.views.calendar" back%}" style="float: left"><<&nbsp;</a><div style="float: left"> {{ date }}</div> &nbsp;<a href="{% url "helidocs.diary.views.calendar" forwards%}" style="float: left">&nbsp;>></a>
    <a title="Back to HomePage" href="{% url "helidocs.diary.views.homepage" %}"><IMG width=210 SRC="/static/helidocs_whitebg.png" ALT="No image to display" style="float: right"></a>
    </caption>
	<colgroup>
		<col class="Mon" />
		<col class="Tue" />
		<col class="Wed" />
		<col class="Thu" />
		<col class="Fri" />
		<col class="Sat" />
        <col class="Sun" />
	</colgroup>
	<thead>
		<tr>
			<th scope="col">Monday</th>
			<th scope="col">Tuesday</th>
			<th scope="col">Wednesday</th>
			<th scope="col">Thursday</th>
			<th scope="col">Friday</th>
			<th scope="col">Saturday</th>
            <th scope="col">Sunday</th>
		</tr>
	</thead>
	<tbody>
    {% for cols in days %}
		<tr class="number">
            {% for c in cols %}
			<td class="title">
                {% if c.day %}
                <a href="javascript:void(0)" onClick="OpenNewEvent('{% url "helidocs.diary.views.grouponadd" c.link%}*5');return false;"><img  border="0" src="/static/groupon.png" alt="New Event" width="12" height="12" /></a>
                <a target="_blank" href={% url "helidocs.diary.views.daytoview" c.link%}>Day
                <a href="javascript:void(0)" onClick="OpenNewEvent('{% url "helidocs.diary.views.calendaradd" c.link%} ');return false;"><img  border="0" src="/static/purpleadd.png" alt="New Event" width="12" height="12" /></a>
                {{c.day}}
                {% endif %}
            </td>
            {% endfor %}
		</tr>
		<tr class="day">
            {% autoescape off %}
            {% for c in cols %}
			<td>{{c.event}}</td>
            {% endfor %}
            {% endautoescape %}
		</tr>
    {% endfor %}
	</tbody>
</table>
<div class="buttons">
<a href="#" onclick="window.print(); return false;">Print Calendar</a>
</div>

{% endblock %}

helidocs/templates/diary/calendar_add.html
{%extends "diary/calendar_base.html" %}
{% load custom_templates %}


{%block title%}Calendar Add{%endblock%}

{% block css %}
    <style type="text/css">
    .eventadd  {color:black;font-family:Calibri,Verdana, Geneva, Tahoma, sans-serif;font-size:90%;}
    .eventadd select {color:black;font-family:Calibri,Verdana, Geneva, Tahoma, sans-serif;font-size:90%;}
    .eventadd input {color:black;font-family:Calibri,Verdana, Geneva, Tahoma, sans-serif;font-size:90%;}

    </style>
    <!-- Loading Theme file(s) -->
    <link rel="stylesheet" href="/static/js_dt_picker/themes/forest.css" />
    <link rel="stylesheet" href="/static/js_dt_picker/themes/layouts/small.css" />

<!-- Loading Calendar JavaScript files -->
    <script type="text/javascript" src="/static/js_dt_picker/src/calendar.js"></script>
<!-- Loading language definition file -->
    <script type="text/javascript" src="/static/js_dt_picker/lang/calendar-en.js"></script>



{% endblock %}

{%block headerscripts%}
<link type="text/css" rel="stylesheet" href="/static/jquery.autocomplete.css">
<script type="text/javascript" src="/static/jquery.min.js"></script>
<script type="text/javascript" src="/static/jquery.validate.min.js"></script>
<script type="text/javascript" src="/static/jquery.autocomplete.js"></script>

<script>

function get_voucher_details()
{
    valv=document.getElementById('id_voucher').value;
    if (valv.indexOf('(voucher)')!=-1){
 //       alert(valv.indexOf('(voucher)'));
        $.get("/get_voucher_contacts/"+valv,
                function(data){
                    $('#id_name').val(data.split("|")[1]);
                    $('#id_mobile').val(data.split("|")[0]);
                    $('#id_seats').val(data.split("|")[2]);
                    $('#id_details').val(data.split("|")[3]);
                }
        );
    }
}
function get_student_details()
{
    valv=document.getElementById('id_name').value;
        $.get("/get_student_contacts/"+valv,
                function(data){
                    if (data){
                    $('#id_mobile').val(data.split("|")[1]);
                    $('#id_email').val(data.split("|")[0]);
                        }
                }
        );

}

$(document).ready(function(){

        $.get("/get_voucher",function(returndata){
        $("#id_voucher").autocomplete(returndata.split("|"));
  });
        document.getElementById("id_voucher").onblur=get_voucher_details;

})

$(document).ready(function(){

        $.get("/get_student",function(returndata){
        $("#id_name").autocomplete(returndata.split("|"));
  });
        document.getElementById("id_name").onblur=get_student_details;

})


function jqueryit(){
$.get("/get_voucher",function(returndata){
        alert(returndata);
        $("#id_voucher").autocomplete(returndata);
});
 }

</script>


    {% if not newevent %}
    <script type="text/javascript">
       opener.location.reload(true);
       opener.focus();
       self.close();
        </script>
    {% endif %}
{%endblock%}


{%block content%}
    <form name="form" method="post" action="." enctype="multipart/form-data">{% csrf_token %}
    <table class="eventadd" width=100%>
        {{ newevent.as_table }}
        <td></td>
    <td class="t1-center" colspan="1">
    <input type="image" width=132 src="/static/update.png" name="submit" value="Submit Event"/>
    </td>
    </table>
    </form>
{%endblock%}

helidocs/templates/diary/calendar_base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>{%block title%}{%endblock%}</title>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-27430461-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
{%block css%}{%endblock%}

{%block headerscripts%}{%endblock%}

{%block headercontent%}{%endblock%}

</head>
<body>

{%block content%}{%endblock%}
<hr>

{%block footer%}{%endblock%}

</body>
</html>

helidocs/templates/diary/calendar_import.html
{%extends "diary/flights_base.html" %}
{% load custom_templates %}

{%block title%}Calendar Import{%endblock%}

{%block css%}
<style type="text/css">
      #import-table th {border: 1px solid #800080;padding-left: 2px;padding-right: 2px;color:black;font-size:70%;text-align:center;}
      #import-table tr {border: 1px solid #800080; font-family:Verdana, Geneva, Tahoma, sans-serif;}
      #import-table td  {border: 1px solid #800080;padding: 0px;color:black;font-size:70%;text-align:center;}
</style>
{%endblock%}

{%block headerscripts%}
{%endblock%}


{%block content%}
    <!-- Header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name"> <a href="{% url "helidocs.diary.views.homepage" %}">Helicopter Docs</a></h1>
        </div>
        <div id="user-tools">
            Welcome,
            <strong>{{  user.username }}</strong>.
           <!-- <a href="/admin/password_change/">
                Change password</a> / -->
            <a href="/logoutuser/">
                Log out</a>
        </div>
    </div>
    <hr>
    {% for breadcrumb in request.breadcrumbs %}
        <a href="{{ breadcrumb.url }}">{{ breadcrumb.name }}</a>{% if not forloop.last %} >> {% endif %}
        {% endfor %}
    <!-- END Header -->

<div align="left" class="fuel">
<table width=98% class="record"  align="center">
<tr><td colspan="3">
</td><td rowspan="3" width="30%"><a title="Back to HomePage" href="{% url "helidocs.diary.views.homepage" %}"><IMG width=210 SRC="/static/helidocs_whitebg.png" ALT="No image to display" style="float: right"></a></td> </tr>

<tr><td width=500px><strong><h2>Calendar Import:</h2></strong></td><td></td></tr>
</table>
    <hr>

<hr>
<table class="sortable" id="import-table" align="left" style="padding: 4px;">
    <tr><th>Error</th><th>Date</th><th>Name</th><th>Activity</th><th>Duration</th><th>Voucher</th><th>Seats</th><th>Long Date</th><th>Original Subject</th></tr>
    {% for p in imports %}
    <tr>
    <td>{{ p.error }}</td>
    <td>{{ p.st|date:"H:i d/m/Y"}}</td>
    <td>{{ p.Name }}</td>
    <td class="right">{{ p.Activity }}</td>
    <td class="right">{{ p.time }}</td>
    <td class="right">{{ p.POVoucher_Number }}</td>
    <td class="right">{{ p.Number_of_Places }}</td>
    <td class="right">{{ p.Date_of_Activity }}</td>
    <td class="right" style="color: #8a2be2;">{{ p.subject }}</td>

    </tr>
    {% endfor %}

</table>
<br><br><br><br>
{% endblock %}